### ISSUE TITLE
Fundamentals endpoints coming back empty. 

### ISSUE THREAD

**Issue by Enericoy** [areed1192/interactive-broker-python-api#10]
Unsure if this is an error on my end or not, but having used both the IBClient and querying the localhost directly I am getting nothing back when using some of the fundamental endpoints, wondering if they maybe have been removed since this code was published?

For example:
**https://localhost:5000/v1/api/iserver/fundamentals/{conid}/summary** and **ib_client.fundamentals_summary** both return a summary for a chosen conid as expected. 

However:
**https://localhost:5000/v1/api/fundamentals/financials/{conid}?type=income&annual=true** and **ib_client.fundamentals_financials** come back as "None" or "Resource not found".

Similarly for **ib_client.fundamentals_key_ratios**, **ib_client.fundamentals_esg**, **ib_client.fundamentals_dividends**, **ib_client.data_analyst_forecast**, nothing is returned. 

I have tried removing and adding the "/iserver/" in the paths to see if maybe it is the wrong path but neither came back with anything. I have tried finding the endpoints by looking at the fundamentals data on my IB account and watching the requests, which are called out to "https://ndcdyn.interactivebrokers.com/tws.proxy/fundamentals/financials/{conid
}?annual=true&type=income" which matches above without the prefix. 

Wondering if this is something others have experienced?

**Comment by 5tomato** [comment]
I have experienced the same thing. I did not find that the above solution resolved the issue. Any update on this?

**Comment by areed1192** [comment]
So it appears that Interactive Brokers has ended access to the Fundamentals Endpoint using the API; as such, I'll be removing the endpoints from the library. I might try to see if the logic holds with this URL:

- https://ndcdyn.interactivebrokers.com/tws.proxy/fundamentals/financials/%7Bconid%7D?annual=true&type=income

Until then, I'm going to make them "private methods" so people don't get confused. I'm also revamping the process for logging in and will provide an option where you can just let me know if the server is already running or not.

**Comment by 5tomato** [comment]
@areed1192 thanks for checking into this! I emailed the IB team about news endpoints that were not on the Restful API documentation, and they said those kinds of endpoints are available through the TWS API, but not yet through the Restful API.

I noticed that you were also using tipranks' api for news. Have you found the quality of their news to be comparable with IB's?
