### ISSUE TITLE
How often do we need to authenticate?

### ISSUE THREAD

**Issue by wuliwei9278** [areed1192/interactive-broker-python-api#14]
I noticed that recently the authentication process is very often like every few hours, is that something common? or how do we fix it?

**Comment by areed1192** [comment]
So, the authentication is handled entirely by the client portal gateway. From what I gathered in the documentation you must log into a session at least once per 24 hours.

**Comment by wuliwei9278** [comment]
Once per 24 hours is tolerable but lately it is like every 3 hours. Is this normal?

**Comment by gmcmicken** [comment]
@wuliwei9278 I am seeing the same thing - every 3 hours. I can't seem to keep the session open longer than this no matter what calls I make to keep it alive, sso/validate, tickle, etc.
