### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'is_server_running'

### ISSUE THREAD

**Issue by centi1** [areed1192/interactive-broker-python-api#15]
Hi, I am getting an error TypeError: __init__() got an unexpected keyword argument 'is_server_running'
any suggestions?

**Comment by gra88hopper** [comment]
me too same thing. any help ?

**Comment by BayoSodeinde** [comment]
yeah I got this error too when I used python from the terminal but when I used from IDE, I'm using PyCharm, it stopped coming up

**Comment by jazarija** [comment]
Can confirm this issue.

While not really answering your question, I was able to run the examples listed on the main page by simply removing this argument.

**Comment by przeroone** [comment]
Found that `pip install interactive-broker-python-web-api` is not the same version as github master branch.

Try `python -m pip install git+https://github.com/areed1192/interactive-broker-python-api@master` solved the problem for me.
