### ISSUE TITLE
401 returned on portfolio_account_positions call

### ISSUE THREAD

**Issue by codingarchercom** [areed1192/interactive-broker-python-api#16]
Hey,
First of all thanks a lot for the repo, it has helped me pickup the interactive apis quite well. I have an issue where by whenever i call portfolio_account_positions i always get a 401. I also get the same on portfolio_account_position. I am using the api_client that you wrote so it does call the account api before it makes this call. I have tried to simulate the same on swagger docs and i get the same response there too. There is nothing in the response body and nothing in the header that i can correct. Do you have any clue on how can this be fixed. Also, yeah i am authenticated. The account calls print an empty [] (array). I can get the market data after this call too.

**Comment by areed1192** [comment]
So recently I noticed the same thing, I'm looking into it and trying to see if they changed one of their endpoints again.
