### ISSUE TITLE
api for BONDS ?

### ISSUE THREAD

**Issue by AshiHarel** [areed1192/interactive-broker-python-api#17]
Hi, 
I am trying to get BONDS info using this api with no success: 
1. When preforming symbol_search for symbols I get items  restricted as BONDS for example with symbol **MNSB**:
Return object: 
[
  {...},
  {
    "issuers": [
      {
        "id": "e3298009",
        "name": "MainStreet Bank"
      }
    ],
    **"conid": 2147483647,**
    "companyHeader": "MainStreet Bank",
    "companyName": "None",
    "symbol": "MNSB",
    "description": "None",
    **"restricted": "BOND",**
    "fop": "None",
    "opt": "None",
    "war": "None",
    "sections": [
      {
        "secType": "BOND"
      }
    ]
  }
]

But I failed to use the object values to receive usable data about the bond. The conid: 2147483647 is the same one for all bonds in IB so no success..

2. In TWS api - https://interactivebrokers.github.io/tws-api/basic_contracts.html#Bonds
    Bond api is documented but is not mentioned in the our limited api -  https://interactivebrokers.com/api/doc.html  
    I did try to use to get bonds info using the CONTRACT endpoint, for example using CUSIP as symbol (as mentioned in TWS api), but with no luck. 

Am I missing something? 
Appreciate any help I can get!

Thanks, 
Ashi

**Comment by AshiHarel** [comment]
I managed to solved this issue myself, with the following request: 

https://localhost:5000/v1/api/iserver/secdef/info?**conid=037833100&sectype=BOND&issuerId=e1432232&symbol=AAPL**
conid=037833100 -is AAPL CUSIP, I just googled it. 
sectype=BOND, issuerId=e1432232 are taken from https://localhost:5000/v1/api/iserver/secdef/search request 
symbol=AAPL is needed as well. 

Hope this helps others. 
Please advise if you would like a pull request to be made with this url request.

**Comment by Matb85** [comment]
Hi @AshiHarel,
A rookie question, do you happen to know how to get the price of the bond? When I try to get "the contract info", I do get a lot of fields, but there isn't anything like a "price" fields. Thank you in advance!

<img width="346" alt="Screenshot 2023-07-10 at 12 24 41" src="https://github.com/areed1192/interactive-broker-python-api/assets/69219238/d8d3f9a6-a0d9-4925-ae4f-f6f74bc60776">
