### ISSUE TITLE
HTTPError  when request fundamentals_financials

### ISSUE THREAD

**Issue by ShaneZhong** [areed1192/interactive-broker-python-api#18]
Hi, I am using the `_fundamentals_financials` and it seems like the end point is no longer working? Please see my code and error message below:

`ib_client._fundamentals_financials(conid='265598',
                                   financial_statement='income',
                                   period='quarter')`

------------
https://localhost:5000/v1/portal/tws.proxy/fundamentals/financials/265598
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-23-be3a6178a755> in <module>
----> 1 ib_client._fundamentals_financials(conid='265598',
      2                                    financial_statement='income',
      3                                    period='quarter')

~/Documents/GitHub/invest_better/ibw_sz/client.py in _fundamentals_financials(self, conid, financial_statement, period)
    932         endpoint = 'tws.proxy/fundamentals/financials/{}'.format(conid)
    933         req_type = 'GET'
--> 934         content = self._make_request(
    935             endpoint=endpoint,
    936             req_type=req_type,

~/Documents/GitHub/invest_better/ibw_sz/client.py in _make_request(self, endpoint, req_type, headers, params, data, json)
    722         elif not response.ok and url != 'https://localhost:5000/v1/portal/iserver/account':
    723             print(url)
--> 724             raise requests.HTTPError()
    725 
    726     def _prepare_arguments_list(self, parameter_list: List[str]) -> str:

HTTPError:

**Comment by areed1192** [comment]
Yeah, I left them in there as private methods in case anyone wanted to try themselves, but as of right now they no longer work.
