### ISSUE TITLE
why would i get the error message: Only 50 simultaneous API historical data requests allowed

### ISSUE THREAD

**Issue by SunHxiao** [areed1192/interactive-broker-python-api#4]
Hello Everyone.
I am very interesting in your github.
I am trading with some stocks.
By the way, I am getting this error message after some time.
![image](https://user-images.githubusercontent.com/56060401/80502805-a76f8680-89a3-11ea-8ec8-39a43b892a8b.png)
How can I fix this error?
I will wait for your favorable reply.
Best regards!

**Comment by areed1192** [comment]
Okay, so you're probably making too many requests. How many requests are you trying to do at once? Additionally how many endpoints are you using?

**Comment by SunHxiao** [comment]
three stocks
reqHistoricalData(
        contract,
        endDateTime='',
        durationStr='1 D',
        barSizeSetting='1 min',
        whatToShow='TRADES',
        useRTH=True,
        formatDate=1,
        keepUpToDate=True)
time.sleep(60)

**Comment by areed1192** [comment]
Are you using your own functions to make the request? I'd have to see the entire program to understand exactly what it's doing. For example, some of the arguments you're passing through aren't correct. So I'm surprised you're getting any data back.

**Comment by SunHxiao** [comment]
ok.
Thanks.
[trade.zip](https://github.com/areed1192/interactive-broker-python-api/files/4546905/trade.zip)

**Comment by areed1192** [comment]
Just an FYI, this repo isn't for the `ib_sync` library. This library is for the 'web-based-api`. The repo you want is [ib_insync](https://github.com/erdewit/ib_insync)

**Comment by SunHxiao** [comment]
But I think that the way is the same.
And I know you are an expert in this field.
Can you help me?

**Comment by areed1192** [comment]
I have never used that library, so I don't know you need to ask the question on that repo, please. I'll be closing this comment now.
