### ISSUE TITLE
news endpoint or conid in client is out of date

### ISSUE THREAD

**Issue by sandybradley** [areed1192/interactive-broker-python-api#8]
Hi, 
Thank you for your work and sharing. I had a test script working yesterday but not today. It seemed the hard coded news endpoint was out of date so I replaced it with an account endpoint ...

line 202 - 204 - commented out
 
line 342 ...
 try:
                    # news_resp = self.data_news(conid='265598')
                    accs = self.portfolio_accounts()
                    if len(accs) > 0:
                        self.authenticated = True

                        #  Log the response.
                        logging.debug('Had to do Account Update Response: {auth_resp}'.format(
                                auth_resp=accs
                            )
                        )
                        break

**Comment by shengjia2020** [comment]
It solved the authentication problem for me! Many thanks!

**Comment by 5tomato** [comment]
@areed1192 Did you access these endpoints with an older version of the clientportal? I can see in your resources folder that you have responses for this endpoint. Were those example responses generated using the Restful API, or accessing the url while logged into the web portal?
